name: fotoshare
services:
  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb-init:/docker-entrypoint-initdb.d
    environment:
      - MARIADB_ROOT_PASSWORD=4AinfoRep-25
      - MARIADB_PASSWORD=4AinfoRep-25
      - MARIADB_USER=ufoto
      - MARIADB_DATABASE=fotoshareDB
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
      - ADMINER_DEFAULT_USER=ufoto
      - ADMINER_DEFAULT_PASSWORD=4AinfoRep-25

  app:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - photo_uploads:/app/uploads/photos
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/fotoshareDB"
      - "SPRING_DATASOURCE_USERNAME=ufoto"
      - "SPRING_DATASOURCE_PASSWORD=4AinfoRep-25"
      - "FOTOSHARE_STORAGE_LOCATION=/app/uploads/photos"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8081 || exit 1
      interval: 5m
      timeout: 10s
      retries: 5
      start_period: 3m
    depends_on:
      mariadb:
        condition: service_healthy

volumes:
  mariadb_data:
  photo_uploads:
